# SMI TCPRoute — canonical example from spec.
# Source: https://github.com/servicemeshinterface/smi-spec/blob/main/apis/traffic-specs/v1alpha4/traffic-specs.md
apiVersion: specs.smi-spec.io/v1alpha4
kind: TCPRoute
metadata:
  name: the-routes
spec:
  matches:
    ports:
      - 3306
      - 6446
